name: Generate cards.json on push

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch (change branch name if needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Zip Honkai.xml into honkai.zip
        run: |
          zip honkai.zip Honkai.xml

      - name: Commit and push changes
        run: |
          git config --local user.name "LunaticCat"
          git add -f cards.json honkai.zip
          git commit -m "Update json file and add honkai.zip" || echo "No changes to commit"
          git push origin main
